version: "3.8"

services:
  budget-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://fepa:fepa123@fepa-postgres:5432/fepa_budget
      - RABBITMQ_URL=amqp://fepa:fepa123@fepa-rabbitmq:5672

    networks:
      - fepa-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  fepa-network:
    name: api-gateway_fepa-network
    external: true

volumes:
  postgres_data:
  rabbitmq_data:
